import { Geist, Geist_Mono } from "next/font/google";
import { assetPath } from "../lib/assetPath";
import "./globals.css";
import Navbar from "../components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: {
//     icon: assetPath("/icons/url_icon.svg"),
//   },
// };
export const metadata = {
  title: "Portal eMasjid  | Sistem Pengurusan Masjid Selangor",
  description:
    "Portal eMasjid  ialah sistem pengurusan pintar masjid untuk permohonan, kemaskini dan pengurusan masjid di Selangor.",
  verification: {
    google: "VwRSVoSz5uqnXdFxtAIT6c7OGyMBP6dZ0JZ7_jXRaD8", // this is from google console 
  },
  icons: {
    icon: assetPath("/icons/url_icon.svg"),
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
